[tool.tartufo]
repo-path = "."
json = true
regex = true
entropy = true

[[tool.tartufo.exclude-path-patterns]]
path-pattern = '^tartufo\.toml$'
reason = 'Tartufo exclusions file contains patterns that should not be counted as findings'

[[tool.tartufo.exclude-entropy-patterns]]
path-pattern = '^\.github/[Ww]orkflows/.*(\.ya?ml)?$'
pattern = 'uses:\s*.*@[a-fA-F0-9]{40}'
reason = 'GitHub Actions version hashes'
scope = 'line'

[[tool.tartufo.exclude-entropy-patterns]]
path-pattern = '^\.pre-commit-config\.ya?ml$'
pattern = 'rev:\s*[a-fA-F0-9]{40}'
reason = 'pre-commit hook version hashes'
scope = 'line'

[[tool.tartufo.exclude-entropy-patterns]]
path-pattern = '^sceptre/templates/s3\.yaml'
pattern = 'role/GD-APPSVCS-LambdaExecutionRole'
reason = 'Lambda Execution Role name/ARN component'
scope = 'word'

[[tool.tartufo.exclude-entropy-patterns]]
path-pattern = '^sceptre/templates/s3\.yaml'
pattern = 'com/AmazonS3/latest/API/RESTBucketGETInventoryConfig'
reason = 'documentation URL fragment'
scope = 'word'

[[tool.tartufo.exclude-entropy-patterns]]
path-pattern = '^README\.md'
pattern = 'com/display/IRKB/Forensic\+Storage\+Phase\+1'
reason = 'documentation URL fragment'
scope = 'word'
