# list dependencies here because a variable depends on it
dependencies:
  - eu-west-1/s3.yaml
  - eu-west-2/s3-replication.yaml

# Where to get the bucket name from using !stack_output_external
storage_bucket_name_output: "{{project_code}}-{{environment}}-eu-west-1-s3::BucketName"
replica_bucket_name_output: "{{project_code}}-{{environment}}-eu-west-2-s3-replication::BucketName"
