# list dependencies here because a variable depends on it
dependencies:
  - eu-west-1/s3.yaml
  - eu-west-2/s3-replication.yaml
storage_bucket_name: "gd-{{DevelopmentTeam}}-{{environment}}-forensic-storage"
replica_bucket_name: "gd-{{DevelopmentTeam}}-{{environment}}-forensic-storage-replica"
