template_path: s3.yaml
parameters:
  ServiceCatalogVersion: 1.10.0
  BucketNameSuffix: "forensic-storage"
  BucketPolicy: Private
  VersioningStatus: "Enabled"
  ExpirationDays: "1460"
  OldVersionExpirationDays: "1460"
  EnableBucketMetrics: "true"
