template_path: s3.yaml
parameters:
  ServiceCatalogVersion: 1.10.0
  BucketPolicy: Private
  VersioningStatus: "Enabled"
  ExpirationDays: "2557"
  OldVersionExpirationDays: "2557"
  EnableBucketMetrics: "true"
