template_path: temp-user-iam-policy.yaml
dependencies:
  - {{environment}}/eu-west-1/s3-raw.yaml
parameters:
  PolicyNameSuffix: "temp-user-iam-policy"
  PolicyJSON: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Action": [
            "s3:Get*",
            "s3:List*",
            "s3:AbortMultipartUpload"
          ],
          "Effect": "Allow",
          "Resource": "*"
        },
        {
          "Action": [
            "s3:PutObject",
            "s3:PutObjectAcl"
          ],
          "Effect": "Allow",
          "Resource": [
            "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-forensic-storage-raw",
            "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-forensic-storage-raw/*"
          ]
        }
      ]
    }
