template:
  type: file
  path: s3.yaml.j2
# we need to manage a stack created in the past because we must preserve existing S3 buckets
stack_name: "{{project_code}}-{{environment}}-{{region}}-s3"
dependencies:
  - eu-west-2/s3-replication.yaml
parameters:
  BucketNameSuffix: "{{BucketNameSuffix}}"
  BucketPolicy: Private
  VersioningStatus: "Enabled"
  ExpirationDays: "1461"
  OldVersionExpirationDays: "1461"
  EnableBucketMetrics: "true"
  BucketOwnerPreferred: "true"
  MoveToStandardIAStorageDays: "180"
  ReplicationBucket: !stack_output_external "{{project_code}}-{{environment}}-eu-west-2-s3-replication::BucketName"
sceptre_user_data:
  # to use your IDE's YAML formatter/linter, just comment out the pipe character in the following line
  # please be sure to restore it before committing your changes
  # this is a multi-line string, so the pipe character is required
  # we are using this to put the YAML directly into the Jinja template so that
  # - we can use both the Jinja2 and CloudFormation template variables
  # - it is easier to maintain when compared to a JSON blob as a string in a YAML file
  # - we do not run up against the 4096 character limit of the CustomBucketPolicy parameter (largely due to indentation)
  custom_bucket_policy: |
    Fn::ToJsonString:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
          Action: s3:*
          Resource:
            - !Sub arn:aws:s3:::gd-${DevelopmentTeam}-${Environment}-${BucketNameSuffix}
            - !Sub arn:aws:s3:::gd-${DevelopmentTeam}-${Environment}-${BucketNameSuffix}/*
        - Effect: Deny
          Principal:
            AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
          Action:
            - s3:Delete*
          Resource:
            - !Sub arn:aws:s3:::gd-${DevelopmentTeam}-${Environment}-${BucketNameSuffix}
            - !Sub arn:aws:s3:::gd-${DevelopmentTeam}-${Environment}-${BucketNameSuffix}/*
          Condition:
            ArnEquals:
              aws:PrincipalArn:
                - !Ref OpsRoleARN
                - !Ref DeployRoleARN
        - Effect: Deny
          Principal:
            AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
          Action:
            - s3:Delete*
          Resource:
            - !Sub arn:aws:s3:::gd-${DevelopmentTeam}-${Environment}-${BucketNameSuffix}
            - !Sub arn:aws:s3:::gd-${DevelopmentTeam}-${Environment}-${BucketNameSuffix}/*
          Condition:
            ArnLike:
              aws:PrincipalArn:
                - !Sub arn:aws:iam::${AWS::AccountId}:user/GD-user-*
        - Effect: Allow
          Principal:
            Service: ssm.amazonaws.com
          Action:
            - s3:Get*
            - s3:List*
            - s3:PutObject*
          Resource:
            - !Sub arn:aws:s3:::gd-${DevelopmentTeam}-${Environment}-${BucketNameSuffix}/ssmLogs
            - !Sub arn:aws:s3:::gd-${DevelopmentTeam}-${Environment}-${BucketNameSuffix}/ssmLogs/*
          Condition:
            StringEquals:
              aws:SourceAccount: {{ analysis_account_id }}
        - Effect: Allow
          Principal:
            AWS: arn:aws:iam::{{ analysis_account_id }}:root
          Action:
            - s3:ListBucket
            - s3:GetObject*
          Resource:
            - !Sub arn:aws:s3:::gd-${DevelopmentTeam}-${Environment}-${BucketNameSuffix}
            - !Sub arn:aws:s3:::gd-${DevelopmentTeam}-${Environment}-${BucketNameSuffix}/*
          Condition:
            StringEquals:
              aws:PrincipalTag/IncidentResponse: ForensicAnalysis
        - Effect: Allow
          Principal:
            AWS: arn:aws:iam::{{ analysis_account_id }}:root
          Action:
            - s3:PutObject
            - s3:DeleteObject
          Resource:
            - !Sub arn:aws:s3:::gd-${DevelopmentTeam}-${Environment}-${BucketNameSuffix}/*/_analysis/*
          Condition:
            StringEquals:
              aws:PrincipalTag/IncidentResponse: ForensicAnalysis
        - Effect: Allow
          Principal:
            AWS: arn:aws:iam::{{ analysis_account_id }}:root
          Action:
            - s3:ListBucket
            - s3:GetObject*
          Resource:
            - !Sub arn:aws:s3:::gd-${DevelopmentTeam}-${Environment}-${BucketNameSuffix}
            - !Sub arn:aws:s3:::gd-${DevelopmentTeam}-${Environment}-${BucketNameSuffix}/*
          Condition:
            ArnEquals:
              aws:PrincipalArn:
                - arn:aws:iam::{{ analysis_account_id }}:role/GD-AWS-USA-GD-RespForens-Ops
        - Effect: Allow
          Principal:
            AWS: arn:aws:iam::{{ analysis_account_id }}:root
          Action:
            - s3:PutObject
            - s3:DeleteObject
          Resource:
            - !Sub arn:aws:s3:::gd-${DevelopmentTeam}-${Environment}-${BucketNameSuffix}/*/_analysis/*
          Condition:
            ArnEquals:
              aws:PrincipalArn:
                - arn:aws:iam::{{ analysis_account_id }}:role/GD-AWS-USA-GD-RespForens-Ops
