template:
  type: file
  path: s3.yaml
dependencies:
  - eu-west-2/s3-replication.yaml
parameters:
  ServiceCatalogVersion: 1.13.1
  BucketNameSuffix: {{BucketNameSuffix}}
  BucketPolicy: Private
  VersioningStatus: "Enabled"
  ExpirationDays: "1461"
  OldVersionExpirationDays: "1461"
  EnableBucketMetrics: "true"
  BucketOwnerPreferred: "true"
  MoveToStandardIAStorageDays: "180"
  ReplicationBucketsJSON: |
    [{"name": "gd-{{DevelopmentTeam}}-{{environment}}-{{BucketNameSuffix}}-replica"}]
  CustomBucketPolicyJSON: |
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "AWS": "arn:aws:iam::{{account_id}}:root"
                },
                "Action": "s3:*",
                "Resource": [
                    "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-{{BucketNameSuffix}}",
                    "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-{{BucketNameSuffix}}/*"
                ]
            },
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": "ssm.amazonaws.com"
                },
                "Action": [
                    "s3:Get*",
                    "s3:List*",
                    "s3:PutObject*"
                ],
                "Resource": [
                    "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-{{BucketNameSuffix}}/ssmLogs",
                    "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-{{BucketNameSuffix}}/ssmLogs/*"
                ],
                "Condition": {
                    "StringEquals": {
                        "aws:PrincipalOrgID": "o-nkgi7akmvi",
                        "aws:SourceAccount": "{{analysis_account_id}}"
                    }
                }
            },
            {
                "Effect": "Allow",
                "Principal": {
                    "AWS": "arn:aws:iam::{{ analysis_account_id }}:root"
                },
                "Action": [
                    "s3:Get*",
                    "s3:List*"
                ],
                "Resource": [
                    "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-{{BucketNameSuffix}}",
                    "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-{{BucketNameSuffix}}/*"
                ],
                "Condition": {
                    "StringEquals": {
                        "aws:PrincipalOrgID": "o-nkgi7akmvi",
                        "aws:PrincipalTag/IncidentResponse": "ForensicAnalysis"
                    }
                }
            },
            {
                "Effect": "Deny",
                "Principal": {
                    "AWS": "*"
                },
                "Action": [
                    "s3:Delete*"
                ],
                "Resource": [
                    "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-{{BucketNameSuffix}}",
                    "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-{{BucketNameSuffix}}/*"
                ],
                "Condition": {
                    "StringEquals": {
                        "aws:PrincipalOrgID": "o-nkgi7akmvi"
                    },
                    "ArnEquals": {
                        "aws:PrincipalArn": [
                            "arn:aws:iam::{{account_id}}:role/GD-AWS-USA-GD-RespStorag-Ops"
                        ]
                    }
                }
            }
        ]
    }
