template:
  type: file
  path: s3.yaml.j2
stack_name: "{{project_code}}-s3-athena"
parameters:
  BucketNameSuffix: athena
  VersioningStatus: "Enabled"
  ExpirationDays: "1"
  OldVersionExpirationDays: "1"
  EnableBucketMetrics: "true"
sceptre_user_data:
  is_replication_target: false
  provisioned_product_name: response-athena-bucket
