template:
  type: file
  path: s3.yaml.j2
parameters:
  BucketNameSuffix: athena
  BucketPolicy: Private
  VersioningStatus: "Enabled"
  ExpirationDays: "1"
  OldVersionExpirationDays: "1"
  EnableBucketMetrics: "true"
  BucketOwnerPreferred: "true"
sceptre_user_data:
  is_replication_target: false
  provisioned_product_name: response-athena-bucket
