template_path: iam-user.yaml
dependencies:
  - {{environment}}/{{region}}/sir-iam-policy.yaml
parameters:
  UserName: "GD-user-sir"
  PolicyName: "CustomPolicy"
  CustomPolicySuffix: "sir-iam-policy"
