template_path: "ec2.yaml"
parameters:
  # This EC2 build includes installing dependencies required for SIFT installation onto the EC2 then backgrounding the SIFT installation processes so they will run on the EC2 instance after the dependency
  # installation is complete. This installation and build process takes ~50 minutes and can be monitored by listing running processes and grepping for "sift" in the process list.
  # This installation uses known good versions of GoLang and SIFT for installation by targeting static versions to pull from websites.
  NameTag: sift-workstation-1
  InstanceType: t3.2xlarge
  AMIImageId: /GoldenAMI/gd-ubuntu20.04/latest
  PrivateSubnetIds: /AdminParams/VPC/PrivateSubnets
  PrivateSecurityGroupId: /AdminParams/VPC/PrivateSG
  TagsCommaDelimitedList: '{"Key":"doNotShutDown", "Value":"false"}'
  ImageOS: linux
  UseUbuntu: "true"
  CustomIAMRoleNameSuffix: "iam-ec2-role"
  # SIFT installation
  CustomUserData: ""
  BlockDeviceMappingsJSON: |-
    [
      {
        "DeviceName": "/dev/sda1",
        "Ebs": {
          "VolumeType": "gp3",
          "DeleteOnTermination": "true",
          "VolumeSize": "500"
        }
      }
    ]
