template_path: s3.yaml
parameters:
  ServiceCatalogVersion: 1.13.1
  BucketNameSuffix: "forensic-storage"
  BucketPolicy: Private
  VersioningStatus: "Enabled"
  ExpirationDays: "1461"
  OldVersionExpirationDays: "1461"
  EnableBucketMetrics: "true"
  BucketOwnerPreferred: "true"
  MoveToStandardIAStorageDays: "180"
  ReadOnlyRoles: "arn:aws:iam::197818030129:role/respforens-custom-iam-ec2-role","arn:aws:iam::${AWS:AccountId}:role/GD-AWS-USA-GD-RespStorag-Ops"
