template:
  type: file
  path: data-lake-local-data-admins.yaml
stack_name: "{{ project_code }}-{{ component_name }}-local-data-admins"
parameters:
  DataLakeAdminRoles:  >-
    [ "GD-AWS-USA-GD-RespStorag-Ops" ]
  GoDaddyLambdaBucket: /AdminParams/Team/GlobalBucket
