template:
  type: file
  path: glue-table.yaml
stack_name: "{{ project_code }}-{{ component_name }}-{{ app_name }}-table"
dependencies:
  - "{{ region }}/glue/{{ app_name }}/database.yaml"
parameters:
  TableType: EXTERNAL_TABLE
  Owner: "{{ account_id }}"
  DatabaseName: "{{ app_name }}"
  TableName: shopperids
  BucketNameSuffix: athena/idsToLookup
  InputFormat: org.apache.hadoop.mapred.TextInputFormat
  OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
  SerializationLibrary: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe
  NumberOfColumns: "1"
  GlueTableColumnNames: ids
  GlueTableColumnTypes: string
  GlueTableColumnComments: shopperIDsToTranslateToCustomerIDs
  SerdeName: ParquetHiveSerDe
  SerdeParametersJson: '{"serialization.format": "1","field.delim": ","}'
  StorageDescriptorParametersJson: >-
    {
      "compressionType": "none",
      "classification": "csv",
      "typeOfData": "file"
    }
