AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  # for the ec2 instance:
  UseUbuntu:
    Type: String
    Description: Specifies if you are using ubuntu image
    Default: false
  ImageOS:
    Type: String
    Description: OS of the image (linux or windows)
    Default: linux
    AllowedValues:
      - linux
      - windows
  NameTag:
    Type: String
    Default: example-box
  InstanceType:
    Type: String
    Description: EC2 Instance Type
    Default: t3.small
  AMIImageId:
    Type: String
    Description: AMI
    Default: /GoldenAMI/gd-amzn2/latest
  PrivateSubnetIds:
    Type: AWS::SSM::Parameter::Value<List<String>>
    Description: SSM parameter referencing the Private subnet IDs
    Default: /AdminParams/VPC/PrivateSubnets
  PrivateSecurityGroupId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::SecurityGroup::Id>
    Description: SSM parameter referencing the Private security group ID
    Default: /AdminParams/VPC/PrivateSG
  CustomIAMRoleNameSuffix:
    Type: String
    Description: (optional) Naming suffix (ex. team-custom-SUFFIX) of Custom IAM Role for instance to run as. Ensure the EC2 service can assume it.
    Default: ""
  TagsCommaDelimitedList:
    Type: String
    Description: (optional) Delimited list string defining a list of tags. Example '{"Key":"test", "Value":"t"},{"Key":"t", "Value":"w"}'
    Default: ""
  CustomUserData:
    Type: String
    Description: (optional) User Data to replace the standard User Data script. Please insert as a single line.
    Default: ""
  BlockDeviceMappingsJSON:
    Type: String
    Description: (optional) JSON string to Specify a block device mapping for an instance.
    Default: "[]"

Resources:
  Instance:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: EC2
      ProvisioningArtifactName: 2.9.0
      ProvisionedProductName: !Sub ${NameTag}-ec2
      ProvisioningParameters:
        # required parameters
        - Key: InstanceType
          Value: !Ref InstanceType
        - Key: AMIImageId
          Value: !Ref AMIImageId
        - Key: VPCSubnetId
          Value: !Select [ 0, !Ref PrivateSubnetIds ]
        - Key: WebServerSecurityGroupIds
          Value: !Ref PrivateSecurityGroupId
        - Key: CustomUserData
          Value: echo 'Hello World'
        - Key: EC2TagName
          Value: !Ref NameTag
        - Key: CustomIAMRoleNameSuffix
          Value: !Ref CustomIAMRoleNameSuffix
        - Key: ImageOS
          Value: !Ref ImageOS
        - Key: UseUbuntu
          Value: !Ref UseUbuntu
        - Key: TagsCommaDelimitedList
          Value: !Ref TagsCommaDelimitedList
        - Key: CustomUserData
          Value: !Ref CustomUserData
        - Key: BlockDeviceMappingsJSON
          Value: !Ref BlockDeviceMappingsJSON
      Tags:
        - Key: "doNotShutDown"
          # change to false if it can be turned off outside of business hours
          Value: "false"
