AWSTemplateFormatVersion: 2010-09-09
Description: Deploys an IAM User
Parameters:
  UserName:
    Type: String
    Description: A name for the IAM user.
  CustomPolicySuffix:
    Type: String
    Description: Suffix name of custom policy.
Resources:
  IAMUser:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: IAMUser
      ProvisioningArtifactName: 3.2.0
      ProvisionedProductName: !Sub ${UserName}-iam-user
      ProvisioningParameters:
        - Key: UserName
          Value: !Ref UserName
        - Key: PolicyName
          Value: "CustomPolicy"
        - Key: CustomPolicySuffix
          Value: !Ref CustomPolicySuffix
      Tags:
        - Key: doNotShutDown
          Value: true
Outputs:
  StackArn:
    Value: !GetAtt IAMUser.CloudformationStackArn
    Description: The ARN of the created cloud formation stack
