Resources:
  LambdaBuildEC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
Version: '2012-10-17'
Statement:
- Effect: Allow
  Action:
  - sts:AssumeRole
  Principal:
    Service:
    - lambda.amazonaws.com
