AWSTemplateFormatVersion: 2010-09-09
Description: Bucket used for replication of objects from s3.yaml bucket

Parameters:
  ServiceCatalogVersion:
    Type: String
    Description: Service Catalog version for S3
  BucketNameSuffix:
    Type: String
    MinLength: 1
    Default: bucket1
    AllowedPattern: "[a-z][a-z0-9-]+[a-z0-9]"
    Description: Unique naming suffix for bucket
  BucketPolicy:
    Type: String
    Description: Bucket ACL to set
    Default: Private
    AllowedValues:
      - Private
      - LogDeliveryWrite
      - AwsExecRead
      - BucketOwnerRead
      - BucketOwnerFullControl
      - PublicRead
      - AuthenticatedRead
  BucketOwnerPreferred:
    Type: String
    Description: Set to true to enable ownership controls with object ownership set to BucketOwnerPreferred. Otherwise the bucket will not have ownership controls so object ownership will default to ObjectWriter.
    Default: false
    AllowedValues:
      - true
      - false
  VersioningStatus:
    Type: String
    Description: Versioning should be enabled unless there is good reason not to.
    Default: Enabled
    AllowedValues:
      - Enabled
      - Suspended
      - Disabled
  MoveToStandardIAStorageDays:
    Type: Number
    Description: (Optional) Days before moving objects to standard Infrequent Access storage. Set to -1 to never move. Defaults to never moving. Ignored if `CustomS3Bucket` is specified.
    Default: -1
  ExpirationDays:
    Type: Number
    Description: (optional) Days before expiring object. Set to -1 to never expire.
    Default: -1
  OldVersionExpirationDays:
    Type: Number
    Description: (optional) Days before expiring outdated object versions. Set to -1 to never expire.
    Default: 180
  EnableBucketMetrics:
    Type: String
    Description: Enable all available bucket metrics.
    Default: false
    AllowedValues:
      - true
      - false
  CustomBucketPolicyJSON:
    Type: String
    Description: Custom JSON S3 Bucket Policy. This will be ignored if DataLakeBucket is true.
    Default: ""

Resources:
  ReplicationS3Bucket:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: S3
      ProvisioningArtifactName: !Ref ServiceCatalogVersion
      ProvisionedProductName: replication-response-storage-bucket
      ProvisioningParameters:
        - Key: BucketNameSuffix
          Value: !Ref BucketNameSuffix
        - Key: BucketPolicy
          Value: !Ref BucketPolicy
        - Key: VersioningStatus
          Value: !Ref VersioningStatus
        - Key: ExpirationDays
          Value: !Ref ExpirationDays
        - Key: OldVersionExpirationDays
          Value: !Ref OldVersionExpirationDays
        - Key: EnableBucketMetrics
          Value: !Ref EnableBucketMetrics
        - Key: BucketOwnerPreferred
          Value: !Ref BucketOwnerPreferred
        - Key: MoveToStandardIAStorageDays
          Value: !Ref MoveToStandardIAStorageDays
        - Key: CustomBucketPolicyJSON
          Value: !Ref CustomBucketPolicyJSON

      Tags:
        - Key: doNotShutDown
          Value: true

Outputs:
  BucketName:
    Description: "Name of created S3 Bucket"
    Value: !Ref ReplicationS3Bucket
