AWSTemplateFormatVersion: 2010-09-09
Description: IAM User for SIR to be able to retrieve metadata and GetObjects from S3 bucket.
Parameters:
  UserName:
    Type: String
    Description: A name for the IAM user.
  PolicyName:
    Type: String
    Description: A policy name.
  CustomPolicySuffix:
    Type: String
    Description: Suffix name of custom policy.
Resources:
  IAMUser:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: IAMUser
      ProvisioningArtifactName: 2.4.2
      ProvisionedProductName: sir-iam-user
      ProvisioningParameters:
        - Key: UserName
          Value: !Ref UserName
        - Key: PolicyName
          Value: !Ref PolicyName
        - Key: CustomPolicySuffix
          Value: !Ref CustomPolicySuffix
      Tags:
        - Key: doNotShutDown
          Value: true
Outputs:
  StackArn:
    Value: !GetAtt IAMUser.CloudformationStackArn
    Description: The ARN of the created cloud formation stack
