AWSTemplateFormatVersion: 2010-09-09
Description: Deploy the SNS Service Catalog Product With Slack Notification
Parameters:
  # Must be provided by env/region specific config
  SnsTopicName:
    Type: String
    Description: SNS Topic Name. This value will be pushed from the configs.yaml pertaining to the region or the account based on the team's requirement
  TeamSlackWebHook:
    Type: String
    Description: Slack webhook for telemetry notifications
    Default: ""
Resources:
  SimpleNotificationService:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: SNS
      ProvisioningArtifactName: 1.0.13
      ProvisionedProductName: threat-sns-bucketSize-notify
      ProvisioningParameters:
        # required parameters
        - Key: SnsTopicName
          Value: !Ref SnsTopicName
        - Key: TeamSlackWebHook
          Value: !Ref TeamSlackWebHook
      Tags:
        - Key: doNotShutDown
          # change to false if it can be turned off outside of business hours
          Value: "true"
