template_path: s3-athena.yaml
dependencies:
  - {{environment}}/us-west-2/dataLakeLinkedDatabase.yaml
parameters:
  BucketNameSuffix: athena
  BucketPolicy: Private
  VersioningStatus: "Enabled"
  ExpirationDays: "1"
  OldVersionExpirationDays: "1"
  EnableBucketMetrics: "true"
  BucketOwnerPreferred: "true"
  ServiceCatalogVersion: 1.20.0
