template_path: s3-data-transfer.yaml
parameters:
  ServiceCatalogVersion: 1.10.0
  BucketNameSuffix: "forensic-storage"
  VersioningStatus: "Enabled"
  ExpirationDays: "2557"
  OldVersionExpirationDays: "2557"
  BucketPolicy: "PublicRead"
  EnableBucketMetrics: "true"
  DataLakeBucket: "false"
