template_path: s3.yaml
parameters:
  ServiceCatalogVersion: 1.13.1
  BucketNameSuffix: {{threatBucketName}}
  BucketPolicy: Private
  ExpirationDays: "365"
  EnableBucketMetrics: "true"
  MoveToStandardIAStorageDays: "90"
  CustomBucketPolicyJSON: |
    {
      "Version": "2012-10-17",
      "Statement": [
          {
              "Effect": "Allow",
              "Principal": {
                  "AWS": "arn:aws:iam::{{accountId}}:root"
              },
              "Action": "s3:*",
              "Resource": [
                  "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-{{threatBucketName}}",
                  "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-{{threatBucketName}}/*"
              ]
          },
          {
              "Effect": "Allow",
              "Principal": {
                  "AWS": "arn:aws:iam::{{threatId}}:root"
              },
              "Action": [
                  "s3:Get*",
                  "s3:List*",
                  "s3:Put*",
                  "s3:Delete*"
              ],
              "Resource": [
                  "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-{{threatBucketName}}",
                  "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-{{threatBucketName}}/*"
              ],
              "Condition": {
                  "StringEquals": {
                      "aws:PrincipalOrgID": "o-nkgi7akmvi"
                    }
                }
            }
        ]
    }
