template_path: s3.yaml
parameters:
  ServiceCatalogVersion: 1.10.0
  VersioningStatus: "Enabled"
  ExpirationDays: "2557"
  OldVersionExpirationDays: "2557"
  BucketPolicy: "PublicRead"
  EnableBucketMetrics: "true"
  DataLakeBucket: "false"
  CustomBucketPolicyJSON:  '[
  {
    "Version": "2012-10-17",
    "Id": "Policy1611277539797",
    "Statement": [
        {
            "Sid": "Stmt1611277535086",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::149976299053:user/poynt/victor"
            },
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::gd-respstorag-dev-forensic-storage/*",
            "Condition": {
                "StringEquals": {
                    "s3:x-amz-acl": "bucket-owner-full-control"
                }
            }
        },
        {
            "Sid": "Stmt1611277877767",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::149976299053:user/poynt/victor"
            },
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::gd-respstorag-dev-forensic-storage"
            }
        ]
    }
  ]'
