template_path: s3.yaml
parameters:
  ServiceCatalogVersion: 1.12.1
  BucketNameSuffix: "forensic-storage"
  BucketPolicy: Private
  VersioningStatus: "Enabled"
  ExpirationDays: "1461"
  OldVersionExpirationDays: "1461"
  EnableBucketMetrics: "true"
  BucketOwnerPreferred: "true"
