template_path: iam-policy.yaml
dependencies:
  - {{environment}}/eu-west-1/s3.yaml
parameters:
  PolicyNameSuffix: "sir-iam-policy"
  PolicyJSON: |
    {
      "Version": "2012-10-17",
      "Statement": [
          {
              "Sid": "VisualEditor0",
              "Effect": "Allow",
              "Action": [
                  "s3:GetObject",
                  "s3:ListBucket"
              ],
              "Resource": [
                  "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-forensic-storage",
                  "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-forensic-storage/*",
                  "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-forensic-storage-replica",
                  "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-forensic-storage-replica/*"
              ]
          },
          {
              "Sid": "VisualEditor1",
              "Effect": "Allow",
              "Action": [
                  "s3:ListAllMyBuckets",
                  "s3:GetBucketLocation"
              ],
              "Resource": "*"
          }
      ]
    }
