template_path: sir-iam-policy.yaml
dependencies:
  - {{environment}}/{{region}}/s3.yaml
parameters:
  PolicyNameSuffix: "sir-iam-policy"
  StorageBucketName: gd-${DevelopmentTeam}-${DevelopmentEnvironment}-${BucketNameSuffix}
