template_path: threat-response-iam-policy.yaml
dependencies:
  - {{environment}}/{{region}}/s3.yaml
parameters:
  PolicyNameSuffix: "threat-response-iam-policy"
  StorageBucketName: gd-${DevelopmentTeam}-${DevelopmentEnvironment}-forensic-storage
