template_path: threat-response-iam-policy.yaml
dependencies:
  - {{environment}}/eu-west-1/s3.yaml
parameters:
  PolicyNameSuffix: "threat-response-iam-policy"
  PolicyJSON: |
    {
        "Version": "2012-10-17",
        "Statement": [{
          "Action": [
            "s3:PutObject"
            ],
          "Effect": "Allow",
          "Resource": "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-forensic-storage/*"
        }
      ]
    }
