template:
  type: file
  path: s3.yaml.j2
# we need to manage a stack created in the past because we must preserve existing S3 buckets
stack_name: "{{project_code}}-{{environment}}-{{region}}-s3-replication"
parameters:
  BucketNameSuffix: "{{BucketNameSuffix}}"
  BucketPolicy: Private
  VersioningStatus: "Enabled"
  ExpirationDays: "1461"
  OldVersionExpirationDays: "1461"
  EnableBucketMetrics: "true"
  BucketOwnerPreferred: "true"
  MoveToStandardIAStorageDays: "180"
  CustomBucketPolicyJSON: |
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "AWS": "arn:aws:iam::{{account_id}}:root"
                },
                "Action": "s3:*",
                "Resource": [
                    "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-{{BucketNameSuffix}}",
                    "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-{{BucketNameSuffix}}/*"
                ]
            },
            {
                "Effect": "Deny",
                "Principal": {
                    "AWS": "arn:aws:iam::{{account_id}}:root"
                },
                "Action": [
                    "s3:Delete*"
                ],
                "Resource": [
                    "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-{{BucketNameSuffix}}",
                    "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-{{BucketNameSuffix}}/*"
                ],
                "Condition": {
                    "ArnEquals": {
                        "aws:PrincipalArn": [
                            "arn:aws:iam::{{account_id}}:role/GD-AWS-USA-GD-RespStorag-Ops"
                        ]
                    }
                }
            },
            {
                "Effect": "Deny",
                "Principal": {
                    "AWS": "arn:aws:iam::{{account_id}}:root"
                },
                "Action": [
                    "s3:Delete*"
                ],
                "Resource": [
                    "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-{{BucketNameSuffix}}",
                    "arn:aws:s3:::gd-{{DevelopmentTeam}}-{{environment}}-{{BucketNameSuffix}}/*"
                ],
                "Condition": {
                    "ArnLike": {
                        "aws:PrincipalArn": [
                            "arn:aws:iam::{{account_id}}:user/*"
                        ]
                    }
                }
            }
        ]
    }
sceptre_user_data:
  is_replication_target: true
