template_path: s3-replication.yaml
parameters:
  ServiceCatalogVersion: 1.13.1
  BucketNameSuffix: "forensic-storage-replica"
  BucketPolicy: Private
  VersioningStatus: "Enabled"
  ExpirationDays: "1461"
  OldVersionExpirationDays: "1461"
  EnableBucketMetrics: "true"
  BucketOwnerPreferred: "true"
  MoveToStandardIAStorageDays: "180"
