name: cirrus-scan

on:
  push:
    branches: [ develop ] 
  schedule:
    - cron: '59 23 1 1/3 *'  
jobs:
  cirrus-scan-dev:
    runs-on: [self-hosted,ir-forensic-storage-runners,ir-forensic,ir-forensic-storage]
    # Config env vars as necessary for the job.
    env:
      AWS_REGION: us-west-2
    # Only run if previous workflow is successful (e.g., tests are green) or it's another event that qualifies.
    #if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v2.3.4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # v1.5.5
        with:
          role-skip-session-tagging: true
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::141785225513:role/GD-AWS-USA-GD-RespStorag-CICD-Deploy
          role-duration-seconds: 7200 # 2 hours
          role-session-name: cirrus-scan

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@2f9f10ea3fa2eed41ac443fee8bfbd059af2d0a4 # 2.2.2
        with:
          registries: ${{ secrets.AUDIT_ACCOUNT_ID }} # See https://github.com/gdcorp-appservices/cirrus-scan-cicd#cirrusscan-container-images for AUDIT_ACCOUNT_ID

      - name: Pull latest CirrusScan container image
        run: |
          docker pull ${{ secrets.AUDIT_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/cirrus-scan-cicd:latest
      # PAT supplied to GITHUB_AUTH below needs full repo access. cirrus-scan-cicd uses it to submit GitHub status webhook.
      - name: Run CirrusScan checks
        run: |
          docker run --rm \
          -e AWS_ACCESS_KEY_ID \
          -e AWS_SECRET_ACCESS_KEY \
          -e AWS_SESSION_TOKEN \
          -e AWS_DEFAULT_REGION \
          -e TASK_LIST='["vulnscan","zaproxy"]' \
          -e GITHUB_URL="https://github.com/" \
          -e GITHUB_AUTH=${{ secrets.CIRRUSSCAN }} \
          -e GITHUB_REPO=gdcorp-infosec/response-forensic-storage \
          -e GITHUB_COMMIT=${GITHUB_SHA} \
          ${{ secrets.AUDIT_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/cirrus-scan-cicd
