name: Code quality check

on:
  pull_request:
    branches: [ main ]

jobs:
  tartufo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # Checkout this repository

      - name: Checkout GoDaddy Actions repo # Checkout shared actions repository gd-actions
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          repository: gdcorp-actions/tartufo
          token: ${{ secrets.REPO_CLONE_TOKEN_SA_PAT }} # PAT with read access to gd-actions/tartufo
          path: tartufo # Relative to github working directory
          ref: v2.1.0
          persist-credentials: false

      - name: Run Tartufo
        uses: ./tartufo # Relative reference to action in gd-actions repository
        with:
          github_token: ${{ secrets.REPO_CLONE_TOKEN_SA_PAT }}

  #Python test not needed at the moment 
  #python-code-check:
  #  needs: tartufo
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout Repository
  #      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

  #    - name: Set up Python 3.9.0
  #      uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6
  #      with:
  #        python-version: 3.9.0
  #        architecture: 'x64'

  #    - name: Setup Python Environment
  #      run: |
  #        python3 -m venv venv
  #        source venv/bin/activate
  #        pip install -U pip
  #        python -m pip install --upgrade pip
  #        pip install -U -r requirements.txt -r requirements-test.txt
          
  #    - name: Python Tests
  #      run: |
  #        source venv/bin/activate
  #        python -m pytest -v

      - name: Setting up AWS user for tests
        uses: aws-actions/configure-aws-credentials@0309c38ebd10f90dfbb3889431bcf4ea38088012
        with:
          aws-access-key-id: ${{ secrets.DEV_PRIVATE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_PRIVATE_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::763338924548:role/GD-AWS-USA-GD-RespStorag-Dev-Private-Deploy
          role-duration-seconds: 3600

    # SPAQ dashboard
    # - name: Coverage upload to KPI Dashboard
    #   uses: ./gd-actions/spaq-quality
    #   with:
    #     service-key: "testing-github-actions-threat"

    # Cirrus Scans
