name: Code quality check

on:
  pull_request:
    branches: [ main ]

jobs:
  tartufo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # Checkout this repository

      - name: Checkout GoDaddy Actions repo # Checkout shared actions repository gd-actions
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          repository: gdcorp-actions/tartufo
          token: ${{ secrets.REPO_CLONE_TOKEN_SA_PAT }} # PAT with read access to gd-actions/tartufo
          path: tartufo # Relative to github working directory
          ref: v2.0.1
          persist-credentials: false

      - name: Run Tartufo
        uses: ./tartufo # Relative reference to action in gd-actions repository
        with:
          github_token: ${{ secrets.REPO_CLONE_TOKEN_SA_PAT }}

      - name: Setting up AWS user for tests
        uses: aws-actions/configure-aws-credentials@0d9a5be0dceea74e09396820e1e522ba4a110d2f
        with:
          aws-access-key-id: ${{ secrets.DEV_PRIVATE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_PRIVATE_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::763338924548:role/GD-AWS-USA-GD-RespStorag-Dev-Private-Deploy
          role-duration-seconds: 1200

    # Cirrus Scans
