name: Code Quality Checks

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  code-quality:
    runs-on:
      group: 6726-storageaccount
      labels:
        - self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633  # v4.1.2

      - name: Run code quality checks (pre-commit, etc.)
        run: make code-quality
