name: Tartufo scan

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  code-quality:
    runs-on:
      group: 6726-storageaccount
      labels:
        - self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2

      - name: Run code quality checks (Tartufo, pre-commit, etc.)
        run: make code-quality
