name: DEV-PRIVATE ResponseStorage - Delete

# Deletes the ResponseStorage main branch from the AWS DEV PRIVATE environment using sceptre.
# This workflow runs on a self-hosted runner

on:
  workflow_dispatch:

jobs:
  delete_from_dev_private:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
        with:
          aws-access-key-id: ${{ secrets.DEV_PRIVATE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_PRIVATE_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::763338924548:role/GD-AWS-USA-GD-RespStorag-Dev-Private-Deploy
          role-duration-seconds: 1200

      - name: Setup python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip
          pip install -U -r requirements.txt

      - name: Run sceptre
        run: |
          source venv/bin/activate
          cd sceptre
          sceptre delete -y dev-private/eu-west-1/s3.yaml
          sceptre delete -y dev-private/us-west-2/sir-iam-user.yaml
          sceptre delete -y dev-private/us-west-2/threat-response-iam-user.yaml
