name: DEV ResponseStorage - Deploy

# Deploys the ResponseStorage resources to the AWS DEV environment using sceptre.
# This workflow runs on a self-hosted runner

# Can only be deployed manually through workflow_dispatch - Select your branch while running.

on:
 workflow_dispatch:

jobs:
  deploy_to_dev:
    runs-on: [self-hosted,ir-forensic-storage-runners,ir-forensic,ir-forensic-storage]

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::539225272086:role/GD-AWS-USA-GD-RespStorag-Dev-Deploy
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Run sceptre
        run: |
          pip install -U sceptre
          cd sceptre
          sceptre launch -y dev/eu-west-1/s3.yaml
          sceptre launch -y dev/us-west-2/sir-iam-user.yaml
          sceptre launch -y dev/us-west-2/threat-response-iam-user.yaml
