name: DEV ResponseStorage - Deploy

# Deploys the ResponseStorage main branch to the AWS DEV environment using sceptre.
# This workflow runs on a self-hosted runner

on:
  workflow_dispatch:

jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::539225272086:role/GD-AWS-USA-GD-RespStorag-Dev-Deploy
          role-duration-seconds: 1200

      - name: Setup python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip
          pip install -U -r requirements.txt

      - name: Run sceptre
        run: |
          source venv/bin/activate
          cd sceptre
          sceptre launch -y dev/eu-west-1/s3.yaml
          sceptre launch -y dev/us-west-2/sir-iam-user.yaml
          sceptre launch -y dev/us-west-2/threat-response-iam-user.yaml
