name: Deploy DEV-PRIVATE

# Deploys the ResponseStorage resources to the AWS DEV PRIVATE environment using sceptre.
# This workflow runs on a self-hosted runner

# Can only be deployed manually through workflow_dispatch - Select your branch while running.

on:
 workflow_dispatch:

jobs:
  deploy_to_dev_private:
    uses: ./.github/workflows/deploy-resources.yaml
    with:
      aws_environment: dev-private
    secrets:
      DEPLOY_ROLE_ARN: ${{ secrets.DEPLOY_ROLE_ARN }}
