name: Deploy DEV

# Deploys the ResponseStorage resources to the AWS DEV environment using sceptre.
# This workflow runs on a self-hosted runner

# Can only be deployed manually through workflow_dispatch - Select your branch while running.

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - develop

jobs:
  deploy_to_dev:
    uses: ./.github/workflows/deploy-resources.yaml
    with:
      aws_environment: dev
    secrets:
      DEPLOY_ROLE_ARN: ${{ secrets.DEPLOY_ROLE_ARN }}
