name: ResponseStorage (DEV)

# Deploys the ResponseStorage main branch to the AWS DEV environment using sceptre.
# This workflow runs on a self-hosted runner

on:
  workflow_dispatch:
  push:
    branches: [ main ] # Trigger workflow on all pushes to main branch

jobs:
  deploy_to_dev:
    runs-on: self-hosted

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::763338924548:role/GD-AWS-USA-GD-RespStorag-Dev-Private-Deploy
          role-duration-seconds: 3600

      - name: Setup python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip
      - name: Install python dependencies
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
          SECURESERVER_ACCESS_KEY_GHC_SA: ${{ secrets.SECURESERVER_ACCESS_KEY_GHC_SA }}
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${SECURESERVER_ACCESS_KEY_GHC_SA}"
          source venv/bin/activate
          pip install -U -r requirements.txt
          ssh-agent -k
      - name: Run sceptre
        run: |
          source venv/bin/activate
          cd sceptre
          sceptre launch -y dev/us-west-2
