name: ResponseStorage (DEV)

# Deploys the ResponseStorage main branch to the AWS DEV environment using sceptre.
# This workflow runs on a self-hosted runner

on:
  workflow_dispatch:

jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@25a956c84d5dd820d28caab9f86b8d183aeeff3d
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0309c38ebd10f90dfbb3889431bcf4ea38088012
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::539225272086:role/GD-AWS-USA-GD-RespStorag-Dev-Deploy
          role-duration-seconds: 3600

      - name: Setup python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip
          pip install -U -r requirements.txt
          
      - name: Run sceptre
        run: |
          source venv/bin/activate
          cd sceptre
          sceptre launch -y dev/us-west-2
