name: Deploy PROD

# Deploys the ResponseStorage resources to the AWS PROD environment using sceptre.
# This workflow runs on a self-hosted runner

# Can only be deployed manually through workflow_dispatch - Select your branch while running.

on:
  workflow_dispatch:
    inputs:
      u_accept:
        description: Enter "accept"
        type: string
        required: true

jobs:
  deploy_to_prod:
    uses: ./.github/workflows/deploy-resources.yaml
    if: github.ref == 'refs/heads/main'
    with:
      aws_environment: prod
      u_accept: ${{ inputs.u_accept }}
    secrets:
      DEPLOY_ROLE_ARN: ${{ secrets.DEPLOY_ROLE_ARN }}
