name: Modify Temp User

on:
  workflow_dispatch:
    inputs:
      aws_environment:
        description: AWS Environment
        type: choice
        options:
          - dev-private
          - dev
          - test
          - prod
      sceptre_action:
        description: Sceptre action to perform
        type: choice
        options:
          - launch
          - delete
        default: launch
      u_accept:
        description: Enter "accept" if running in prod; not checked otherwise
        type: string
        required: false
  workflow_call:
    inputs:
      aws_environment:
        type: string
        required: true
      sceptre_action:
        type: string
        required: true
      u_accept:
        type: string
        required: false
    secrets:
      DEPLOY_ROLE_ARN:
        required: true

env:
  AWS_ENVIRONMENT: "${{ inputs.aws_environment }}"
  SCEPTRE_ACTION: "${{ inputs.sceptre_action }}"

jobs:
  sceptre_action:
    environment: "${{ inputs.aws_environment }}"
    runs-on: [self-hosted,incident-response,response-forensic-storage,deploy]

    steps:
      - name: Check u_accept for running in prod
        env:
          U_ACCEPT: "${{ inputs.u_accept }}"
        if: "${{ inputs.aws_environment == 'prod' }}"
        run: |
          [[ "${U_ACCEPT}ed" == "accepted" ]]

      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Setup runner
        run: make setup

      # This logs us in to the ${{ inputs.aws_environment }} account's deploy role
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # v2.0.0
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      # use of "${SCEPTRE_ACTION}" is safe because we are using an intermediate environment variable
      - name: Run sceptre
        run: make "${SCEPTRE_ACTION}-temp-iam-user" "SCEPTRE_ACTION_ARGS=-y"
