name: Deploy Temp Users

# Deploys the IAM User "temp-user" to the AWS PROD environment using sceptre.
# This workflow runs on a self-hosted runner

on:
  workflow_dispatch:
    inputs:
      aws_environment:
        description: AWS Environment
        type: choice
        options:
          - dev-private
          - dev
          - test
          - prod
      u_accept:
        description: Enter "accept" if running in prod; not checked otherwise
        type: string
        required: false
  workflow_call:
    inputs:
      aws_environment:
        type: string
        required: true
      u_accept:
        type: string
        required: false
    secrets:
      DEPLOY_ROLE_ARN:
        required: true

jobs:
  deploy_temp_user:
    uses: ./.github/workflows/temp-user.yaml
    with:
      aws_environment: ${{ inputs.aws_environment }}
      sceptre_action: launch
      u_accept: ${{ inputs.u_accept }}
    secrets:
      DEPLOY_ROLE_ARN: ${{ secrets.DEPLOY_ROLE_ARN }}
