name: Delete Temp Users

# Deletes the temporyary IAM User from all AWS environments
# This workflow runs on a self-hosted runner

on:
  schedule:
    - cron: '59 23 * * *'
jobs:
  delete_temp_user:
    uses: ./.github/workflows/temp-user.yaml
    strategy:
      fail-fast: false
      matrix:
        aws_environment:
          - dev-private
          - dev
          - test
          - prod
    with:
      aws_environment: ${{ matrix.aws_environment }}
      sceptre_action: delete
      u_accept: accept
    secrets:
      DEPLOY_ROLE_ARN: ${{ secrets.DEPLOY_ROLE_ARN }}
