name: Deploy TEST

# Deploys the ResponseStorage resources to the AWS TEST environment using sceptre.
# This workflow runs on a self-hosted runner

on:
  workflow_run:
    workflows: ["Code quality check"]
    branches: [main]
    types: [completed]

jobs:
  deploy_to_test:
    runs-on: [self-hosted,ir-forensic-storage-runners,ir-forensic,ir-forensic-storage]

    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::745293682974:role/GD-AWS-USA-GD-RespStorag-Test-Deploy
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Run sceptre
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip
          pip install -U sceptre
          cd sceptre
          sceptre launch -y test/eu-west-1/s3.yaml
          sceptre launch -y test/us-west-2/sir-iam-user.yaml
          sceptre launch -y test/us-west-2/threat-response-iam-user.yaml
