name: Delete Temp User (TEST)

# Deletes the IAM User "temp-user" from the AWS TEST environment using sceptre.
# This workflow runs on a self-hosted runner

on:
  workflow_dispatch:

jobs:
  delete_temp_user_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@25a956c84d5dd820d28caab9f86b8d183aeeff3d

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0d9a5be0dceea74e09396820e1e522ba4a110d2f
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::745293682974:role/GD-AWS-USA-GD-RespStorag-Test-Deploy
          role-duration-seconds: 1200

      - name: Setup python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip
          pip install -U -r requirements.txt

      - name: Run sceptre
        run: |
          source venv/bin/activate
          cd sceptre
          sceptre delete -y test/us-west-2/temp-user-iam-user.yaml
