name: Deploy Temp User (TEST)

# Deploys the IAM User "temp-user" to the AWS TEST environment using sceptre.
# This workflow runs on a self-hosted runner

on:
  workflow_dispatch:

jobs:
  deploy_temp_user_test:
    runs-on: [self-hosted,ir-forensic-storage-runners,ir-forensic,ir-forensic-storage]

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::745293682974:role/GD-AWS-USA-GD-RespStorag-Test-Deploy
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Setup python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip
          pip install -U -r requirements.txt

      - name: Run sceptre
        run: |
          source venv/bin/activate
          cd sceptre
          sceptre launch -y test/us-west-2/temp-user-iam-user.yaml
