name: Deploy TEST

# Deploys the ResponseStorage resources to the AWS TEST environment using sceptre.
# This workflow runs on a self-hosted runner

on:
  workflow_run:
    workflows: ["Code quality check"]
    branches: [main]
    types: [completed]

jobs:
  deploy_to_test:
    uses: ./.github/workflows/deploy-resources.yaml
    with:
      aws_environment: test
    secrets:
      DEPLOY_ROLE_ARN: ${{ secrets.DEPLOY_ROLE_ARN }}
