name: Threat - Deploy

# Deploys the Threat teams S3 bucket, a Cloudwatch alarm to monitor for S3 bucket size, and a SNS topic to post messages to the Threat team's Slack channel if the S3 bucket size is over the set threshold using sceptre.
# This workflow runs on a self-hosted runner

on:
 workflow_dispatch:

jobs:
  deploy_to_dev_private:
    runs-on: [self-hosted,ir-forensic-storage-runners,ir-forensic,ir-forensic-storage]

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::763338924548:role/GD-AWS-USA-GD-RespStorag-Dev-Private-Deploy
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Run sceptre
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip
          pip install -U sceptre
          cd sceptre
          sceptre launch -y dev-private/us-west-2/threat-SNSSlack.yaml

  deploy_to_dev:
    runs-on: [self-hosted,ir-forensic-storage-runners,ir-forensic,ir-forensic-storage]

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::539225272086:role/GD-AWS-USA-GD-RespStorag-Dev-Deploy
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Run sceptre
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip
          pip install -U sceptre
          cd sceptre
          sceptre launch -y dev/us-west-2/threat-SNSSlack.yaml
